# Generated by Django 2.2.6 on 2020-05-29 21:48

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, max_length=299, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='useruploads')),
            ],
            options={
                'ordering': ('filename',),
                'permissions': (('manage_items', 'Manage items.'),),
            },
        ),
    ]
