# Generated by Django 2.2.6 on 2020-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='filename',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
