# Generated by Django 2.2.6 on 2019-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0109_auto_20191006_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
