# Generated by Django 2.2.6 on 2019-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0111_auto_20191128_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=299, null=True),
        ),
    ]
